export const abbrToState = {
  AL: { state: 'Alabama', abbr: 'AL', fips: '01' },
  NE: { state: 'Nebraska', abbr: 'NE', fips: '31' },
  AK: { state: 'Alaska', abbr: 'AK', fips: '02' },
  NV: { state: 'Nevada', abbr: 'NV', fips: '32' },
  AZ: { state: 'Arizona', abbr: 'AZ', fips: '04' },
  NH: { state: 'New Hampshire', abbr: 'NH', fips: '33' },
  AR: { state: 'Arkansas', abbr: 'AR', fips: '05' },
  NJ: { state: 'New Jersey', abbr: 'NJ', fips: '34' },
  CA: { state: 'California', abbr: 'CA', fips: '06' },
  NM: { state: 'New Mexico', abbr: 'NM', fips: '35' },
  CO: { state: 'Colorado', abbr: 'CO', fips: '08' },
  NY: { state: 'New York', abbr: 'NY', fips: '36' },
  CT: { state: 'Connecticut', abbr: 'CT', fips: '09' },
  NC: { state: 'North Carolina', abbr: 'NC', fips: '37' },
  DE: { state: 'Delaware', abbr: 'DE', fips: '10' },
  ND: { state: 'North Dakota', abbr: 'ND', fips: '38' },
  DC: { state: 'District of Columbia', abbr: 'DC', fips: '11' },
  OH: { state: 'Ohio', abbr: 'OH', fips: '39' },
  FL: { state: 'Florida', abbr: 'FL', fips: '12' },
  OK: { state: 'Oklahoma', abbr: 'OK', fips: '40' },
  GA: { state: 'Georgia', abbr: 'GA', fips: '13' },
  OR: { state: 'Oregon', abbr: 'OR', fips: '41' },
  HI: { state: 'Hawaii', abbr: 'HI', fips: '15' },
  PA: { state: 'Pennsylvania', abbr: 'PA', fips: '42' },
  ID: { state: 'Idaho', abbr: 'ID', fips: '16' },
  PR: { state: 'Puerto Rico', abbr: 'PR', fips: '72' },
  IL: { state: 'Illinois', abbr: 'IL', fips: '17' },
  RI: { state: 'Rhode Island', abbr: 'RI', fips: '44' },
  IN: { state: 'Indiana', abbr: 'IN', fips: '18' },
  SC: { state: 'South Carolina', abbr: 'SC', fips: '45' },
  IA: { state: 'Iowa', abbr: 'IA', fips: '19' },
  SD: { state: 'South Dakota', abbr: 'SD', fips: '46' },
  KS: { state: 'Kansas', abbr: 'KS', fips: '20' },
  TN: { state: 'Tennessee', abbr: 'TN', fips: '47' },
  KY: { state: 'Kentucky', abbr: 'KY', fips: '21' },
  TX: { state: 'Texas', abbr: 'TX', fips: '48' },
  LA: { state: 'Louisiana', abbr: 'LA', fips: '22' },
  UT: { state: 'Utah', abbr: 'UT', fips: '49' },
  ME: { state: 'Maine', abbr: 'ME', fips: '23' },
  VT: { state: 'Vermont', abbr: 'VT', fips: '50' },
  MD: { state: 'Maryland', abbr: 'MD', fips: '24' },
  VA: { state: 'Virginia', abbr: 'VA', fips: '51' },
  MA: { state: 'Massachusetts', abbr: 'MA', fips: '25' },
  VI: { state: 'Virgin Islands', abbr: 'VI', fips: '78' },
  MI: { state: 'Michigan', abbr: 'MI', fips: '26' },
  WA: { state: 'Washington', abbr: 'WA', fips: '53' },
  MN: { state: 'Minnesota', abbr: 'MN', fips: '27' },
  WV: { state: 'West Virginia', abbr: 'WV', fips: '54' },
  MS: { state: 'Mississippi', abbr: 'MS', fips: '28' },
  WI: { state: 'Wisconsin', abbr: 'WI', fips: '55' },
  MO: { state: 'Missouri', abbr: 'MO', fips: '29' },
  WY: { state: 'Wyoming', abbr: 'WY', fips: '56' },
  MT: { state: 'Montana', abbr: 'MT', fips: '30' },
}
